Add JSX pragma
cyclejs/react-dom pull request #3
Opened 2019-06-01 19:05 UTC by sliptype

As described in https://github.com/cyclejs/react/pull/3 this PR adds a JSX pragma to allow rendering React components using JSX in Cycle:

```js
import { jsxFactory } from '@cycle/react-dom';

function view(state$: Stream<State>): Stream<ReactElement> {
    return state$.map(({ count }) => (
        <div>
            <h2>Counter: {count}</h2>
            <button sel="add">Add</button>
            <button sel="subtract">Subtract</button>
        </div>
    ));
}
```

2019-06-03 08:35 UTC, staltz commented
Thanks for the PR! Some comments inline...

2019-06-03 17:15 UTC, sliptype commented
No problem!

Could you double check that you submitted the comments, I don't see any

2019-06-04 09:43 UTC, staltz requested changes

2019-06-04 09:43 UTC, staltz commented on readme.md
> +          ['transform-react-jsx', { pragma: jsxFactory.createElement' }],
There is a dangling single quote in this line that is breaking the markdown syntax afterwards

2019-06-04 09:43 UTC, staltz commented on readme.md
> +          ['transform-react-jsx', { pragma: jsxFactory.createElement' }],
@sliptype

2019-06-06 01:28 UTC, sliptype commented on readme.md
> +          ['transform-react-jsx', { pragma: jsxFactory.createElement' }],
@sliptype good catch! fixed in 27832ba

2019-06-06 22:30 UTC, staltz approved these changes

2019-06-06 22:31 UTC, merged

2019-06-06 22:31 UTC, staltz commented
Thank you @sliptype! Great PR, nice bonus with the tests